#ifndef ARKANOID_CONFIG_H
#define ARKANOID_CONFIG_H

#define GAME_FPS    60
#define GAME_FPS_MS (1000 / GAME_FPS)
#define FPS_TARGET  60

#define SCREEN_WIDTH  600
#define SCREEN_HEIGHT 600

#define VAUS_MAX_SIZE      8
#define ANIMATION_TIMER_MS 150

#define BALL_EFFECT 25

#define LEVEL_WIDTH  13
#define LEVEL_HEIGHT 14

#endif // ARKANOID_CONFIG_H
