#ifndef ARKANOID_CONFIG_H
#define ARKANOID_CONFIG_H

#define GAME_FPS    60
#define GAME_FPS_MS (1000 / GAME_FPS)
#define FPS_TARGET  60

#define SCREEN_WIDTH  600
#define SCREEN_HEIGHT 600

#define VAUS_MAX_SIZE             8
#define ANIMATION_TIMER_MS        150
#define DIRECTION_CHANGE_TIMER_MS 500
#define LASER_RELOAD_TIME_MS      1200
#define CATCH_BALL_RELOAD_TIME_MS 1000

#define BALL_EFFECT 25
#define BALL_SPEED  7.0

#define MAX_LEVELS 5

#define LEVEL_OFFSET_Y 150
#define LEVEL_WIDTH    13
#define LEVEL_HEIGHT   16

#define BRICK_WIDTH  32
#define BRICK_HEIGHT 16

#define GAME_BORDER_TOP 50
#define GAME_BORDER_X   (SCREEN_WIDTH - BRICK_WIDTH * LEVEL_WIDTH) / 2

#define MAX_ENTITIES 50

#define DISPLAY_SHADOWS true
#define SHADOW_OFFSET   5

#endif // ARKANOID_CONFIG_H
